Remove macos-12 4.08.1 build  === ERROR while compiling sail_json_backend.0.17 =============================  File "src/sail_json_backend/json.ml", line 97, characters 5-23:  97 |   if String.starts_with ~prefix:"\"" qs && String.ends_with ~suffix:"\"" qs then            ^^^^^^^^^^^^^^^^^^  Error: Unbound value String.starts_with
  - This error message is indicative of an outdated version of OCaml.
  - This issue occurs on the "macos-12" target exclusively.
  - Since the work being done here is not platform-specific, disable the macos-12 platform.