Remove macos-12 4.08.1 build
GitHub CI "build" Action often fails on target "macos-12" with errors like:
```
=== ERROR while compiling sail_json_backend.0.17 =============================
     File "src/sail_json_backend/json.ml", line 97, characters 5-23:
     97 |   if String.starts_with ~prefix:"\"" qs && String.ends_with ~suffix:"\"" qs then
               ^^^^^^^^^^^^^^^^^^
     Error: Unbound value String.starts_with
```

  - This error message is indicative of an outdated version of OCaml.
  - Support in OCaml for String.starts_with arrived in OCaml 4.13, which was released almost 2 years ago (2021-09-24).
  - This issue occurs on the "macos-12" target exclusively.
  - Since the work being done here is not platform-specific and is at the level of "proof-of-concept", we can disable the "macos-12" platform and move on.